apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: coffee-route
  namespace: default
spec:
  parentRefs:
  - name: shared-gateway
  hostnames:
  - "cafe.example.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: coffee-service-v1
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: /
      headers:
      - name: version
        value: v2
    backendRefs:
    - name: coffee-service-v2
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tea-route
  namespace: tea
spec:
  parentRefs:
  - name: shared-gateway
    namespace: default
  hostnames:
  - "tea.example.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: tea-service-v1
      port: 80
      weight: 90
    - name: tea-service-v2
      port: 80
      weight: 10